server:
  port: 8082
mybatis:
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.yong.user.entity.*
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/K8S_USER?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
logging:
  level:
    "com.yong.user.dao": debug
