spring:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/01spring_jdbc
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE
