spring:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/03spring_data_jpa
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    show-sql: true
